#! /usr/bin/env bash

version=$(date +%Y.%m.%d)

# Get the power and minlucks from the Minlucks spreadsheet.
curl -s 'https://docs.google.com/spreadsheets/d/13hKjNDFTFR3rTkmQzyi3d4ZDOlQJUvTfWPDQemmFW_Y/gviz/tq?tqx=out:csv&gid=0' > effs.csv

# Convert the csv to json and replace the escaped quotes.
jq -cR 'split("\",\"")' effs.csv > effs2.csv
sed 's/\\"//g' effs2.csv > effs.csv
jq -csf csv2json.jq effs.csv | jq > effs.json

# # Reformat the json to be an array of objects in the format {"<mouse>": {"power": <power>, "minlucks": [<minlucks>]}}
jq -s '.[0][] | {(.Mouse):{ power: .Power, effs: [.Arcane, .Draconic, .Forgotten, .Hydro, .Parental, .Physical, .Shadow, .Tactical, .Law, .Rift]}}' effs.json > effs2.json
jq -s 'add' effs2.json > effs.json

# # Create the minlucks.js file.
minlucks=$(cat effs.json)

echo "// ==UserScript==
// @name        MouseHunt Minlucks
// @description Minlucks and power for MouseHunt, from Google Sheets, to power the multiple mini-CRE scripts.
// @version     $version
// @license     MIT
// @author      brap
// @namespace   bradp
// @match       https://www.mousehuntgame.com/*
// @icon        https://i.mouse.rip/cheese.png
// @run-at      document-end
// @grant       none
// ==/UserScript==

window.minlucks = $minlucks;" > minlucks.js

# Clean up.
rm effs2.csv
rm effs.csv
rm effs.json
rm effs2.json

# git add minlucks.js
# git commit -m "Update minlucks.js to $version"

# git tag -a "$version" -m "Update minlucks.js to $version" -f

# git push origin main
# git push origin "$version" -f
# npm version "$version"
# npm publish
