#! /usr/bin/env bash

version=$(date +%Y.%m.%d)

# Get the power and minlucks from the Minlucks spreadsheet
curl -s 'https://docs.google.com/spreadsheets/d/13hKjNDFTFR3rTkmQzyi3d4ZDOlQJUvTfWPDQemmFW_Y/gviz/tq?tqx=out:csv&sheet=MP+Effs' > effs.csv

# Convert the CSV to JSON
jq -cR 'split(",")' effs.csv | jq -csf csv2json.jq | jq > effs.json
rm effs.csv

# Remove the escaped quotes
sed 's/\\\"//g' effs.json > effs2.json

# Remove the ∞ symbols
sed 's/∞//g' effs2.json > effs.json

# Reformat the json to be an array of objects in the format {"<mouse>": {"power": <power>, "minlucks": [<minlucks>]}}
jq -s '.[0][] | {(.["Mouse"]):{ power: .["Mouse Power"], effs: [.["Arcane"], .["Draconic"], .["Forgotten"], .["Hydro"], .["Physical"], .["Shadow"], .["Tactical"], .["Law"], .["Rift"]]}}' effs.json > effs2.json
jq -s 'add' effs2.json > effs.json
rm effs2.json

minlucks=$(cat effs.json)
rm effs.json

echo "// ==UserScript==
// @name        MouseHunt Minlucks
// @description Minlucks and power for MouseHunt, from Google Sheets, to power the multiple mini-CRE scripts.
// @version     $version
// @license     MIT
// @author      brap
// @namespace   bradp
// @match       https://www.mousehuntgame.com/*
// @icon        https://i.mouse.rip/cheese.png
// @run-at      document-end
// @grant       none
// ==/UserScript==

window.minlucks = $minlucks;" > minlucks.js

git add minlucks.js
git commit -m "Update minlucks.js to $version"

git tag -a "$version" -m "Update minlucks.js to $version" -f

git push origin main
git push origin "$version" -f
npm version "$version"
npm publish
